### ISSUE TITLE
Missing Icon on Mp4

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#128]
Check out: https://archivesphere-qa.dlt.psu.edu/files/x633f100h#.VdtOISxVhBc

The icon is missing
![screen shot 2015-08-24 at 1 02 39 pm](https://cloud.githubusercontent.com/assets/1599081/9446606/920d268a-4a60-11e5-96b0-4fdff895442d.png)

**Comment by awead** [comment]
Updating `app/views/generic_files/_media_display.html.erb` to the latest from Sufia fixes this. We probably missed this file during the upgrade process.
