### ISSUE TITLE
Uploading 50 files and only 11 show up in the accession

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#130]
I upload the spec fixtures directory via my Computer upload.  That should create an accession with about 50 files in it.  My first try I go 11.  My second try I got 14 files.

first: https://archivesphere-qa.dlt.psu.edu/accessions/th83kz323
second: https://archivesphere-qa.dlt.psu.edu/accessions/0v8380566

**Comment by mtribone** [comment]
I'm also experiencing this issue. When I try to add the files again, they are listed in my accession after upload. Yay! However when I go back to dashboard and then back through my collection and accession the new files no longer appear in my list.

**Comment by mjgiarlo** [comment]
Bizarre! Is this happening only in the QA environment, or also locally? @hectorcorrea @awead

**Comment by awead** [comment]
Local upload doesn't use jobs. Perhaps it should.

**Comment by hectorcorrea** [comment]
We think this will fix it https://github.com/psu-stewardship/archivesphere/pull/139

**Comment by hectorcorrea** [comment]
We have not been able to replicate the issue with the new locking code in place.
