### ISSUE TITLE
About page is empty

### ISSUE THREAD

**Issue by nty5001** [psu-stewardship/archivesphere#135]
The About page (https://archivesphere-qa.dlt.psu.edu/about/) appears empty. Viewed in Chrome and Firefox, though suspect that other browsers also show the same.

The link to Edit expands the page and offers a Save button, but no editing fields appear.

**Comment by awead** [comment]
TinyMC editor isn't working in QA. It does locally, though. I smell an asset pipeline problem.

**Comment by awead** [comment]
Yeah, this is a pipeline issue. The plugin.js isn't getting loaded.

**Comment by awead** [comment]
@cam156  SS is using version 4.1.6 of the tinymce-rails gem, whereas AS is only using 4.0.28. Not sure if that's the problem or not, but since we're in gem freeze, we could opt to punt on this or just put static text in the page.
