### ISSUE TITLE
File added with incorrect accession

### ISSUE THREAD

**Issue by hectorcorrea** [psu-stewardship/archivesphere#140]
I uploaded two files and one of them blows up when going to the show page for the file. Upon further inspection I noticed that the "accession" for the file points in fact to a **collection**

This is what the Rails console shows for a good file
```
irb(main):009:0> gf1 = GenericFile.find("archivesphere:zp38wc60z")
=> #<GenericFile pid: "archivesphere:zp38wc60z", blah blah blah >

irb(main):010:0> gf1.accessions.first
=> #<Accession pid: "archivesphere:wh246s128", depositor: "hjc14", title: nil, date_uploaded: Tue, 25 Aug 2015, date_modified: Tue, 25 Aug 2015, description: "", creator: [], contributor: [], based_near: [], part_of: [], publisher: [], date_created: [], subject: [], resource_type: [], rights: [], identifier: [], language: [], tag: [], related_url: [], accession_num: "two files again", disk_num: nil, disk_image: nil, disk_label: nil, accession_type: "Disk Media">

```

Now notice the file in question. The accessions.first is pointing to the collection!

```
irb(main):011:0> gf2 = GenericFile.find("archivesphere:9k41zd49s")
=> #<GenericFile pid: "archivesphere:9k41zd49s", blah blah blah >

irb(main):014:0> gf2.accessions.first
=> #<Collection pid: "archivesphere:5d86p0224", depositor: "hjc14", title: "hector was here", date_uploaded: Mon, 17 Aug 2015, date_modified: Tue, 25 Aug 2015, description: nil, creator: [], contributor: [], based_near: [], part_of: [], publisher: [], date_created: [], subject: [], resource_type: [], rights: [], identifier: [], language: [], tag: [], related_url: [], collection_num: nil>
irb(main):015:0>
```

**Comment by hectorcorrea** [comment]
I've just realized that the accession for the file in question was the second element of the collection, not the first one. That's an easy fix. PR coming.

**Comment by hectorcorrea** [comment]
@awead I've submitted a PR to handle this but on a second though I am even wondering is it even "normal" for `generic_file.accessions` to have a mix of Collection and Accession objects. Is that the way is supposed to work?

**Comment by hectorcorrea** [comment]
This is what the accessions for the problematic file shows

```
irb(main):031:0> gf2.accessions[0]
=> #<Collection pid: "archivesphere:5d86p0224", depositor: "hjc14", title: "hector was here", date_uploaded: Mon, 17 Aug 2015, date_modified: Tue, 25 Aug 2015, description: nil, creator: [], contributor: [], based_near: [], part_of: [], publisher: [], date_created: [], subject: [], resource_type: [], rights: [], identifier: [], language: [], tag: [], related_url: [], collection_num: nil>

irb(main):032:0> gf2.accessions[1]
=> #<Accession pid: "archivesphere:wh246s128", depositor: "hjc14", title: nil, date_uploaded: Tue, 25 Aug 2015, date_modified: Tue, 25 Aug 2015, description: "", creator: [], contributor: [], based_near: [], part_of: [], publisher: [], date_created: [], subject: [], resource_type: [], rights: [], identifier: [], language: [], tag: [], related_url: [], accession_num: "two files again", disk_num: nil, disk_image: nil, disk_label: nil, accession_type: "Disk Media">
irb(main):033:0> 
```

**Comment by hectorcorrea** [comment]
This is the accession where this happens: https://archivesphere-qa.dlt.psu.edu/accessions/wh246s128

**Comment by awead** [comment]
@hectorcorrea accessions are collections, except in name. In fact, in some places we're actually using the word "collection" when what we really mean is "accession" so we don't have to duplicate code.

It is not normal for a collection object to be intermingled with accessions when calling `.accessions` on a file. Is there a test that replicates this issue?

**Comment by hectorcorrea** [comment]
@awead There is no test for this. I just happen to run into this issue when testing the system in QA. I am wondering if this a result of the missing lock logic since this version does not have it still and I was uploading two files at once.

**Comment by awead** [comment]
@hectorcorrea so I tried doing something similar on my local machine and didn't see this problem. Although the PR is fine, I'd really like to make sure this isn't happening because if it is, it's bad. Right now, I'm going to chalk it up to the locking mechanism that, until today, wasn't in place. Maybe re-running all tests tomorrow might prove that?

**Comment by hectorcorrea** [comment]
:+1:

**Comment by hectorcorrea** [comment]
I have not been able to replicate this issue so I will close it as well as the pull request.
