### ISSUE TITLE
Network upload broke with latest Browse Everything

### ISSUE THREAD

**Issue by hectorcorrea** [psu-stewardship/archivesphere#183]
The ability to upload files via the Network Upload option broke with the latest version of Browse Everything. 

The culprit seems to be this line: https://github.com/projecthydra-labs/browse-everything/blob/master/app/assets/javascripts/browse_everything/behavior.js.coffee#L207 

The new version of Browse Everything is setting the `value` property of the checkbox to "0" or "1". In the previous version the `checked` property is what was set instead (and the `value` was left untouched.) 

Because the `value` property is being set to "0" or "1", when the user submits the form, the browser passes "0"s and "1"s to the server as opposed to the names of the files/folders that were checked (which is what was stored in the `value` property). 

This code used to work because it relied on some functionality from Browse Everything. Given that the tree in Browse Everything and the one for the Network Upload are totally unrelated I believe we should update the JavaScript for the tree in the Network upload to not borrow the check/uncheck functionality from Browse Everything.

**Comment by awead** [comment]
If the patch to BrowseEverything fixes this, we should be able revert the changes made to address this. See #185.
