### ISSUE TITLE
accession show does not show disk image

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#189]
If I upload a disk image for an accession, then the show and the edit should display it.  Currently only the edit displays the image.
![screen shot 2015-10-20 at 10 25 24 am](https://cloud.githubusercontent.com/assets/1599081/10610341/6150ca7e-7715-11e5-8f5e-51d65bc8444c.png)
![screen shot 2015-10-20 at 10 25 11 am](https://cloud.githubusercontent.com/assets/1599081/10610394/9827cdcc-7715-11e5-88fc-289c91f7180c.png)

**Comment by hectorcorrea** [comment]
This might be because of the changes to speed up the accession show. I am probably not fetching from Solr the field needed for the image.
