### ISSUE TITLE
Preview and Preservation for PDF documents

### ISSUE THREAD

**Issue by hectorcorrea** [psu-stewardship/archivesphere#23]
The links for "Preview" and "Preservation" don't work for PDF files in ArchiveSphere. This is happening in production V1.0.

Clicking on the "Preview" link opens a new tab but the content is "We're sorry, but something went wrong." Other file formats seem to work OK (e.g. Word docs, JPG)

**Comment by awead** [comment]
This appears to be working now locally.

**Comment by hectorcorrea** [comment]
:+1:
