### ISSUE TITLE
Validate the Bag contents against the bag

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#34]
When I upload a bag
The system will verify the checksums in the bag against the uploaded files
If there is an error I will be notifed

Original Story:

As an archivist, when “bag” is selected as the transfer type, I would like to validate the contents of ingested bags based on the manifest included in the bag, in order to verify the integrity of the data being ingested. 

Original Done Criteria:

The system compares the checksums found in the manifest-md5.txt file with MD5 calculated by the system. 

The validation is logged as an event in the metadata associated with objects from the ingest.

Document the validation as an event, and delete the manifest-md5.txt

**Comment by cam156** [comment]
There is a bagit gem in ruby that can validate the bag

**Comment by cam156** [comment]
The validation could be done based on a bag being validated on any type of upload in sufia

**Comment by cam156** [comment]
What happens when the bag does not validate

**Comment by hectorcorrea** [comment]
When a bag is not valid the error is recorded and the user is notified in the notifications tab.
