### ISSUE TITLE
Unzip compressed files uploaded during ingest

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#35]
When I upload a compressed file
Then the system should extract all the included files
And generate a GenericFile for each 
And the activity stream for each file should include an event for the extraction
And the original file should be discarded

Original Story:

As an archivist, I would like for ArchiveSphere to unpack any compressed objects encountered on ingest (tar, zip, etc.), so that the files contained within can be managed and preserved at the object level.

Original Done Criteria:

The system unpacks and processes compressed objects encountered during ingest, discards the original compressed file.

The decompression is recorded as an event in the metadata for each associated object.

The original file can be deleted

**Comment by cam156** [comment]
We are assuming this is a single layer of extraction

**Comment by cam156** [comment]
We are assuming there will be no bag, and if they are  they are treated as regular files.

**Comment by hectorcorrea** [comment]
This is how it works now. When using the Network Explorer to upload files if the user selects a zip file (or a zip file is found in a folder being uploaded) the system extracts the files in the zip file and uploads them. The path of the files in the zip file are honored. The zip file is not uploaded to ArchiveSphere. Each of the extracted files will have the name of the zip that it came from in a (new) property called Source Container and displayed on the file details page.
