### ISSUE TITLE
Network Location File Review

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#36]
When I Upload a directory from the netowrk file location
Then I should be able to see what is in each folder

Original Story:

As an archivist, I would like the ability to review the contents of folders selected for ingest prior to finalizing the ingest

Original Done Criteria:

I can review the entire tree structure (including folder names, file names, and file sizes) of an ingest prior to finalizing it by expanding and collapsing the tree.

**Comment by cam156** [comment]
When we are in the controller we have access to the server location.  In the view we should be showing the information discovered by the controller.

**Comment by hectorcorrea** [comment]
Fixed in #48
