### ISSUE TITLE
Deselect File from Network Upload Directory

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#37]
When I upload files from a network drive
And I view a tree of the data inside a folder
Then I should be able to deselect files from the ingest before uploading

Original Story:

As an archivist, I would like the ability to remove certain files or folders from being included in the ingest (e.g. DS_store files).

Original Done Criteria:

I can mark certain files to not be ingested from the tree structure.

Unselect single item in a directory selected on the network server location.

**Comment by cam156** [comment]
dependent on #36

**Comment by hectorcorrea** [comment]
Fixed in #48
