### ISSUE TITLE
Where should recent documents go?

### ISSUE THREAD

**Issue by awead** [psu-stewardship/archivesphere#56]
Currently, in https://archivesphere.dlt.psu.edu/catalog there "Recently Uploaded" and "My Latest". This piggybacks off of a feature in the Sufia 3.0 homepage which is no longer there in 5.0. Seems like this listing should be moved to the dashboard. @mtribone thoughts?

**Comment by mtribone** [comment]
Yeah, man. Sounds good.

**Comment by awead** [comment]
away.
