### ISSUE TITLE
New Accession Breadcrumb

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#79]
The Accession New page does not show the current Collection you are creating the accession into.

This occurs when I create a new Collection from the desktop and then save the new collection and get forwarded to the new Accession page.

![screen shot 2015-08-11 at 1 56 37 pm](https://cloud.githubusercontent.com/assets/1599081/9205554/dd374b84-4030-11e5-8c00-8a8dccd3b0f5.png)

**Comment by awead** [comment]
@cam156 When you create a new accession, we're passing the collection_id in the URL. In order to get the collection name, we'd need to make a solr call prior or during the #new action in the accessions controller. Is it work the extra overhead?

**Comment by hectorcorrea** [comment]
Fixed in https://github.com/psu-stewardship/archivesphere/commit/6e1685fb92d0359b7eae93fa9e088ef21dfd3a37 

![screen shot 2015-08-17 at 1 51 01 pm](https://cloud.githubusercontent.com/assets/568286/9311867/3578899c-44e7-11e5-8c30-f2752096beda.png)

**Comment by hectorcorrea** [comment]
Fixed in #112
