### ISSUE TITLE
Upload does not make sense on dashboard

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#81]
An upload can not occur unless you are inside an ingest.  Remove this button from the dahsboard

![screen shot 2015-08-11 at 2 00 52 pm](https://cloud.githubusercontent.com/assets/1599081/9205663/853286d2-4031-11e5-9a3d-9c1dd831bb04.png)

**Comment by awead** [comment]
Rename to ingest and this will fix #82 as well.
