### ISSUE TITLE
When I create a Collection, the ingest should be included in the collection

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#84]
You can see the ingest is correctly created and seems to belong to my collection
![screen shot 2015-08-11 at 2 09 21 pm](https://cloud.githubusercontent.com/assets/1599081/9205879/afcbfde6-4032-11e5-8c32-09a63d9ecb97.png)

But when I click on the collection the ingest is not a part of the collection

![screen shot 2015-08-11 at 2 09 32 pm](https://cloud.githubusercontent.com/assets/1599081/9205877/ad8a3c14-4032-11e5-85c2-750824973d73.png)

**Comment by cam156** [comment]
The accession also shows up in the unassigned accessions (https://archivesphere-qa.dlt.psu.edu/accessions/gt54kn002)

![screen shot 2015-08-11 at 2 12 12 pm](https://cloud.githubusercontent.com/assets/1599081/9205992/4076cfe2-4033-11e5-9242-2740d65b979a.png)

**Comment by cam156** [comment]
An update!  When fils get added to the accession then the file shows up in the collection.  There must be a missing step in solr or soemthing

**Comment by awead** [comment]
Yeah, I saw this yesterday too. Don't know why that's happening.
