### ISSUE TITLE
Deleting an accession is not deleting the inclosed files

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#86]
When I have an Accession that contains files
And I delete the accession
Then the files contained should also be deleted

https://archivesphere-qa.dlt.psu.edu/files/t435gc96m is a file that exists even though the accession was deleted

**Comment by awead** [comment]
@cam156 I can't replicate this locally. I have model and controller tests that are verifying files get deleted when accessions do.

**Comment by awead** [comment]
@cam156 ok, I ran a resolrization job on QA and could delete accessions and file, also created a new accession with a file and deleted it successfully too. Maybe it's fixed? Or was related to resolrization?
