### ISSUE TITLE
The icon in the browser tab is gone

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#87]
The one on the left is QA and the one on the right is production 

![screen shot 2015-08-11 at 2 33 29 pm](https://cloud.githubusercontent.com/assets/1599081/9206463/003e1dd8-4036-11e5-834f-4986678ad237.png)

**Comment by hectorcorrea** [comment]
Fixed in this commit https://github.com/psu-stewardship/archivesphere/commit/de8c8dfdf27e7f89c34a619cc8cea2df88bab5b4
