### ISSUE TITLE
adding files via Browse Everything does not set the accession number

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#92]
When I go to an Accession
And I upload files via browse everything
And I am redirected to the Accession
Then the accession should include the files

I never see the files I add from browse everything in my accession.  I get both emails and notifiations saying they have been uploaded, but the files do not show up.

**Comment by cam156** [comment]
Notification:
<img width="1048" alt="screen shot 2015-08-12 at 8 08 48 am" src="https://cloud.githubusercontent.com/assets/1599081/9223578/6d8fac74-40c9-11e5-82fa-76bd71f753f5.png">

Accession screen without the files:
<img width="740" alt="screen shot 2015-08-12 at 8 09 03 am" src="https://cloud.githubusercontent.com/assets/1599081/9223581/6f89d8a6-40c9-11e5-8625-d596ceae772c.png">

**Comment by cam156** [comment]
Editing the accession metadata DOES NOT make the files show up.  I would guess the accession number is never getting set.

**Comment by awead** [comment]
Yep, accession is not getting set, but the files are making it in. I believe the latter problem was due to resque-pool issues, but we still need to address the accession_id issue.
