### ISSUE TITLE
Adding files via Network Server file ingest does not set the accession number

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#93]
When I choose and Accession
And I click Add Files
And I choose Files from the Network Server Location Tab
Then I should see the files in the accession

I get notification and emails that the files uploaded successfully but they do not show up in the accession

Notification:
<img width="963" alt="screen shot 2015-08-12 at 8 16 12 am" src="https://cloud.githubusercontent.com/assets/1599081/9223734/bef33bb6-40ca-11e5-8f36-fbf9ce421be2.png">

No files in Accession:
<img width="577" alt="screen shot 2015-08-12 at 8 15 51 am" src="https://cloud.githubusercontent.com/assets/1599081/9223735/c1846314-40ca-11e5-8d63-4204ca3f2778.png">

**Comment by cam156** [comment]
Editing the Accession's metadata causes the files to show up.  My guess is the information is being set, but no sent to solr.

**Comment by awead** [comment]
related to #84?

**Comment by awead** [comment]
Not sure if it's related to #84 but it's definitely a resque-pool issue. Restarting resque-pool locally fixed the issue. Will confirm in QA.

**Comment by awead** [comment]
Confirmed this is working in QA
