### ISSUE TITLE
Can not open folders in accession view

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#97]
I can open the first level of folders, but I can not open the second level of folders.  This may be related to the style issue #90 
This is an issue as you can no longer get access to files under a folder: https://archivesphere-qa.dlt.psu.edu/accessions/gt54kn002

**Comment by awead** [comment]
@cam156 this is padding issue. If you decrease the padding on the caret, it'll work, so just some CSS touchup needed here.
