### ISSUE TITLE
PDF Thumbnail, Preview and Preservation links do not work

### ISSUE THREAD

**Issue by cam156** [psu-stewardship/archivesphere#98]
Check out this file: https://archivesphere-qa.dlt.psu.edu/files/4j03cz64w

Just uploaded pdf but the thumbnail is black and the preview and preservation links do not work

**Comment by cam156** [comment]
This may be an existing issue (there is some indication of that int he notes on the testing ticket), but it looks like some PDFs are ok in the system.

**Comment by hectorcorrea** [comment]
The issue with the preview not working is fixed in #116.
I added a separate ticket #117 to deal the missing thumbnails since it's a bigger issue.
